#!/usr/bin/env python3
"""
An asynchronous comprehension that takes no arguments.
but collect a list of 10 random numbers using an async comprehensing 
over async_generator, then return the list of 10 random numbers.
"""
from typing import List
from importlib import import_module as using
async_generator = using('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Asynchronous comprehension returns a list of 10 floats
    generated by the async_generator function.

    Returns:
        List[float]: a list of floats generated by the async_generator.
    """
    return [num async for num in async_generator()]
